music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  
  resources :bands
  resources :albums
  resources :tracks
  
end

music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :band_id,:title,:year,presence: true
  
  belongs_to :band,
  foreign_key: :band_id,
  primary_key: :id,
  class_name: :Band
  
  
  has_many :tracks,
  foreign_key: :album_id,
  primary_key: :id,
  class_name: :Track
  
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
  
  has_many :albums,
  foreign_key: :band_id,
  primary_key: :id,
  class_name: :Album
  
  
end

music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :title,:album_id,:ord, presence: true
  
  
  belongs_to :album,
  foreign_key: :album_id,
  primary_key: :id,
  class_name: :Album
  
end   

music_app/app/models/user.rb
class User < ApplicationRecord
  after_initialize do 
      self.session_token ||= User.generate_session_token
    end
    
  validates :email, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :email, :session_token, :password_digest, uniqueness: true 
  
  attr_reader :password
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)  
  end
  
  def self.find_by_credentials(email,password)
    @user = User.find_by(email: email)
    if @user && @user.is_password?(password)
      return @user
    end
    nil
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])

    if @album
      render :show
    else
      redirect_to bands_url
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])

    if @album.update(album_params)
      redirect_to band_url(@album.band)
    else
      render :edit
    end
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band)
   else
      render :new
    end
  end
  
  def destroy
    @album = Album.find_by(id: params[:id])
    @album.delete
  end


  private
  def album_params
    params.require(:album).permit(:title, :year, :live)
  end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  
  helper_method :current_user
  helper_method :logged_in?
  
  
  def login(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def current_user
    @user = User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  

  
  
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])

    if @band
      render :show
    else
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
   else
      render :new
    end
  end
  
  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy!
  end


  private
  def band_params
    params.require(:band).permit(:name)
  end

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(user_params[:email],user_params[:password])
    if user
      login(user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Wrong password or email"]
      render :new
    end
  end
  
  def destroy
    logout
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
  
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      # msg = UserMailer.welcome_email(@user)
      # msg.deliver_now
      redirect_to user_url(@user)

    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
  
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    '<input
      type="hidden"
      name="authenticity_token"
      value=#{form_authenticity_token}
    />'.html_safe
  end
  
  
end

music_app/app/views/albums/_form.html.erb
<% if action == :edit %>
  <% action_url = album_url(album)%>
<% else %>
  <% action_url = albums_url %>
<% end %>

<form action="<%= action_url %>" method="post">
   <!-- <%# if album.persisted? %> -->
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="title">Title</label>
  <input id="title" type="text" name="album[title]" value="<%= album.title %>">
  
  <br><br>

  <label for="live">Live or Studio</label><br>
  <input id="live" type="radio" name="album[live]" value="true" <%= album.live == "true" ? "checked" : ""%>> Live<br>
  <input id="live" type="radio" name="album[live]" value="false" <%= album.live == "false" ? "checked" : ""%>> Studio<br>

<br><br>

  <label for="band">Band</label>
  <select id="band" name="album[band_id]">
    
    <% Band.all.each do |band| %>
    <option value="<%=band.id%>"   ><%=band.name%></option>
    <% end %>
  </select>

<br><br>

  <input type="submit" value="<%= action == :edit ? 'update album' : 'add album'%>">
</form>

music_app/app/views/albums/edit.html.erb
<h1>Edit Album!</h1>

<%= render 'form', album: @album, action: :edit %>

music_app/app/views/albums/new.html.erb
<h1>New Album!</h1>

<%= render 'form', album: @album, action: :new %>

music_app/app/views/albums/show.html.erb
<style>
table, th, td {
    border: 1px solid black;
}
</style>
<h1>Check out this Album! </h1>

<table style="width:80%" >

  <tr>
    <th>Band</th>
    <th>Title</th>
    <th>year</th>
  </tr>
  <tr >
    <td><%= @album.band.name %></td>
    <td><%= @album.title %></td>
    <td><%= @album.year %></td>
    

  </tr>
</table>

<a href="<%= edit_album_url(@album) %>">Edit this album!</a>

<a href="<%= album_url(@album)%>", data-method ='delete'> Delete this album!</a>

<a href="<%= band_url(@album.band) %>">Show me the band this album belongs to</a>

music_app/app/views/bands/_band.html.erb
<li>
  <%= band.name %> 
  <a href="<%= band_url(band.id) %>">Check this band out!</a>
  <br>
  <br>
  <br>
</li>

music_app/app/views/bands/_form.html.erb
<% if action == :edit %>
  <% action_url = band_url(band)%>
<% else %>
  <% action_url = bands_url %>
<% end %>

<form action="<%= action_url %>" method="post">
   <!-- <%# if band.persisted? %> -->
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="band[name]" value="<%= band.name %>">

<br><br>

  <input type="submit" value="<%= action == :edit ? 'update band' : 'add band'%>">
</form>

music_app/app/views/bands/edit.html.erb
<h1>Edit Band!</h1>

<%= render 'form', band: @band, action: :edit %>

music_app/app/views/bands/index.html.erb
<h1>All the bands!</h1>

<ul>
  <%= render @bands %>
  
  
</ul>

<a href="<%= new_band_url %>">Add a new band!</a>

music_app/app/views/bands/new.html.erb
<h1>New Band!</h1>

<%= render 'form', band: @band, action: :new %>

music_app/app/views/bands/show.html.erb
<style>
table, th, td {
    border: 1px solid black;
}
</style>
<h1>Check out this band! </h1>

<table style="width:80%" >

  <tr>
    <th>Name</th>
    <% if @band.albums != nil %>
      <% @band.albums.each do |album| %>
        <th>album.title</th>
      <% end %>
    <% end %>
  </tr>
  <tr >
    <td><%= @band.name %></td>
    <% if @band.albums != nil %>
      <% @band.albums.each do |album| %>
        <td>album.year</td>
      <% end %>
    <% end %>
    

  </tr>
</table>

<a href="<%= edit_band_url(@band) %>">Edit this band!</a>

<a href="<%= band_url(@band)%>", data-method ='delete'> Delete this band!</a>

<a href="<%= new_album_url %>">add a new album!</a>

<a href="<%= bands_url %>">Show me all the bands!</a>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
    <style>
      header {
        font-size: 50px;
        font-style:italic;
        font-variant: small-caps
      }
    </style>
  
  </head>

  <body>
    <header> Music App </header>
    
      <% if current_user %>
       <h2> Welcome, <%= current_user.email %>!</h2>
       <form action="<%= session_url %>" method="post">
         <input type="hidden" name="_method" value="delete">
         <input type="submit" value="Log Out">
       </form>
      <% else %>
        <%= link_to "Register a new account", new_user_url %>
      <% end %>
   
   <br>
   <br>
   
      <% if flash[:errors] %>
       <% flash[:errors].each do |error| %>
        <%= error %>
       <% end %>
      <% end %>
      <%= yield %>
  </body>
  
  <footer>
    <p> Welcome to the world of music <p>
    <%= yield :footer %>
  </footer>
</html>

music_app/app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <!-- <%= auth_token %> -->
  <label for="email">Email:</label>
  <input
    type="text"
    name="user[email]"
    id="email"
    value="<%= @user.email%>">
  <br>
  <br>
  <label for="password">Password: </label>
  <input
    type="text"
    name="user[password]"
    id="password"
    value="">
  <br>
  <br>

  <input type="submit" value="Create Account">
</form>
<% content_for :footer do  %>
  Exciting stuff awaits
<% end %>

music_app/app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<a href= "#"> go back </a>